Various updates
dortania/OpenCore-Legacy-Patcher pull request #1109
Opened 2023-10-06 01:06 UTC by crystall1nedev

Opening for @techpro-services, this PR fixes small bugs around documentation.

2023-10-06 02:45 UTC, Jazzzny requested changes

2023-10-06 02:45 UTC, Jazzzny commented on docs/PATCHEXPLAIN.md
> +* NVIDIA Web Drivers Binaries
Please list webdriver bundles for consistency

2023-10-06 02:45 UTC, Jazzzny commented on docs/PATCHEXPLAIN.md
> +  * ATIRadeonX2000.kext
Add note for AMD issue resolution

2023-10-06 02:45 UTC, Jazzzny commented on docs/TROUBLESHOOTING.md
> +find “/Volumes/Macintosh HD/Library/Extensions” -name “*.kext” -not -name “HighPoint*” -exec rm -rf {} \;
SoftRAID should also be kept

2023-10-20 02:17 UTC, closed without merging

2023-10-20 02:17 UTC, crystall1nedev commented
Was told by the original owner of the repo that this PR should be closed.