Add MacBookPro5,3 to TESTED.md
dortania/OpenCore-Legacy-Patcher pull request #136
Opened 2021-04-10 04:45 UTC by kommtzeitkonrad

2021-04-10 21:56 UTC, khronokernel requested changes

2021-04-10 21:56 UTC, khronokernel commented on docs/TESTED.md
> +| MacBookPro5,3 | <span style="color:#30BCD5"> YES </span> | kommtzeitkonrad | - Stock model <br/>- Patcher version 0.0.22 |
`<span style="color:#30BCD5"> YES </span>` should be replaced with `^^` to have proper formatting in the with the site

2021-04-10 21:56 UTC, khronokernel commented
PR looks good to me, have a small change requested but otherwise will merge. Thanks for the PR!

2021-04-11 02:40 UTC, kommtzeitkonrad commented
Thank you for how amazing this patcher has become!
I must say that I would really like to get my hands on the early developer preview of the GPU acceleration patches to test it on the MBP5,3 and my good old HD3000-powered Hackintosh. :-)

2021-04-11 02:45 UTC, merged

2021-04-11 02:45 UTC, khronokernel commented
Awesome thanks for the PR! Are you available on discord? Currently all our testing is on the Unsupported Mac discord, as it's easier for us to consolidate testing. If so, I can add you to the beta channel. Just need to know your discord username

2021-04-11 02:53 UTC, kommtzeitkonrad commented
kommtzeitkonrad#0254 :-)